---
title: "MD-HT3"
author: "Diego-Fabian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Análisis exploratorio 

```{r train}
library(dplyr)
if (!requireNamespace("Hmisc", quietly = TRUE)) {
  install.packages("Hmisc")
}
library(Hmisc)
datos  <- read.csv("train.csv")
```


```{r }
datos  <- read.csv("train.csv")
# Crear un dataframe con las variables, descripciones y tipos de variable
# Extraer los nombres de las variables
variables <- colnames(datos)
descripcion <- c("Identificador unico","Identifica el tipo de vivienda implicada en la venta.", "Identifica la clasificación general de zonificación de la venta.", "Pies lineales de la calle conectada a la propiedad.", "Tamaño del lote en pies cuadrados", "Tipo de calle de acceso a la propiedad", "Tipo de callejón de acceso a la propiedad", "Forma general de la propiedad", "Planitud de la propiedad", "Tipo de servicios disponibles", "Configuración de la parcela", "Pendiente de la propiedad", "Ubicaciones físicas dentro de los límites de la ciudad de Ames", "Proximidad a varias condiciones", "Proximidad a varias condiciones (si hay más de una)", "Tipo de vivienda", "Estilo de la vivienda", "Califica el material y el acabado general de la vivienda", "Valora el estado general de la vivienda", "Fecha de construcción original", "Fecha de remodelación (la misma que la fecha de construcción si no hay remodelaciones ni ampliaciones)", "Tipo de tejado", "Material del tejado", "Revestimiento exterior de la casa", "Revestimiento exterior de la casa (si hay más de un material)", "Tipo de revestimiento de mampostería", "Área de revestimiento de mampostería en pies cuadrados", "Evalúa la calidad del material en el exterior", "Evalúa el estado actual del material en el exterior", "Tipo de cimentación", "Evalúa la altura del sótano", "Evalúa el estado general del sótano", "Se refiere a las paredes de la planta baja o del jardín", "Calificación de la superficie acabada del sótano", "Pies cuadrados acabados tipo 1", "Calificación de la superficie acabada del sótano (si hay varios tipos)", "Pies cuadrados acabados de tipo 2", "Pies cuadrados sin terminar de la superficie del sótano", "Total de pies cuadrados de superficie del sótano", "Tipo de calefacción", "Calidad y estado de la calefacción", "Aire acondicionado central", "Sistema eléctrico", "Pies cuadrados del primer piso", "Pies cuadrados del segundo piso", "Pies cuadrados acabados de baja calidad (todas las plantas)", "Superficie habitable por encima del nivel del suelo en pies cuadrados", "Baños completos del sótano", "Sótano medio baño", "Baños completos sobre rasante", "Medios baños por encima del grado", "Dormitorios sobre rasante (NO incluye dormitorios en sótano)", "Cocinas sobre rasante", "Calidad de la cocina", "Total de habitaciones sobre rasante (no incluye baños)", "Funcionalidad de la vivienda (se asume como típica a menos que se justifiquen deducciones)", "Número de chimeneas", "Calidad de la chimenea", "Ubicación del garaje", "Año de construcción del garaje", "Acabado interior del garaje", "Tamaño del garaje en capacidad de coches", "Tamaño del garaje en metros cuadrados", "Calidad del garaje", "Estado del garaje", "Calzada pavimentada", "Superficie de cubierta de madera en pies cuadrados", "Superficie de porche abierto en pies cuadrados", "Superficie del porche cerrado en metros cuadrados", "Superficie del porche para tres estaciones en metros cuadrados", "Screen porch área en pies cuadrados", "Superficie de la piscina en metros cuadrados", "Calidad de la piscina", "Calidad de la valla", "Característica miscelánea no incluida en otras categorías", "Valor de la característica miscelánea", "Mes vendido (MM)", "Año de venta (AAAA)", "Tipo de venta", "Condición de venta", "Precio venta")

tipos_variables <- c("numérica", "categórica", "categórica", "numérica", "numérica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "numérica", "numérica", "numérica", "numérica", "categórica", "categórica", "categórica", "categórica", "categórica", "numérica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "categórica", "numérica", "categórica", "numérica", "numérica", "numérica", "categórica", "categórica", "categórica", "categórica", "numérica", "numérica", "numérica", "numérica", "numérica", "numérica", "numérica", "numérica", "numérica", "numérica", "categórica", "numérica", "categórica", "numérica", "categórica", "categórica", "numérica", "categórica", "numérica", "numérica", "categórica", "categórica", "categórica", "numérica", "numérica", "numérica", "numérica", "numérica", "numérica", "categórica", "categórica", "categórica", "numérica", "numérica", "numérica", "categórica", "categórica", "numérica")

# Crear el dataframe con la información
tabla_variables <- data.frame(Variable = variables,
                              Descripción = descripcion,
                              Tipo = tipos_variables )

print(tabla_variables)
```



```{r train}

# Campos donde se mide por calificaciones:
#       Ex	Excellent
#       Gd	Good
#       TA	Typical/Average
#       Fa	Fair
#       Po	Poor
#       NA	No

columnas_calificaciones <- c("Id", "ExterQual", "ExterCond", "Foundation", "BsmtQual", "BsmtCond", "HeatingQC", "KitchenQual", "FireplaceQu", "GarageQual", "GarageCond", "PoolQC")

datos_procesados_calificaciones <- datos[, columnas_calificaciones]

print(datos_procesados_calificaciones)


```

``` {r mapeo}
datos <- datos %>%
  mutate(ExterCond = case_when(
    ExterCond == "Ex" ~ 5,
    ExterCond == "Gd" ~ 4,
    ExterCond == "TA" ~ 3,
    ExterCond == "Fa" ~ 2,
    ExterCond == "Po" ~ 1,
    TRUE ~ 0
  )) %>%
    mutate(ExterQual = case_when(
    ExterQual == "Ex" ~ 5,
    ExterQual == "Gd" ~ 4,
    ExterQual == "TA" ~ 3,
    ExterQual == "Fa" ~ 2,
    ExterQual == "Po" ~ 1,
    TRUE ~ 0
  )) %>%
  mutate(Foundation = case_when(
    Foundation == "BrkTil" ~ 6,
    Foundation == "CBlock" ~ 5,
    Foundation == "PConc" ~ 4,
    Foundation == "Slab" ~ 3,
    Foundation == "Stone" ~ 2,
    Foundation == "Wood" ~ 1,
    TRUE ~ NA_real_
  )) %>%
  mutate(BsmtQual = case_when(
    BsmtQual == "Ex" ~ 5,
    BsmtQual == "Gd" ~ 4,
    BsmtQual == "TA" ~ 3,
    BsmtQual == "Fa" ~ 2,
    BsmtQual == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(BsmtCond = case_when(
    BsmtCond == "Ex" ~ 5,
    BsmtCond == "Gd" ~ 4,
    BsmtCond == "TA" ~ 3,
    BsmtCond == "Fa" ~ 2,
    BsmtCond == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
    mutate(BsmtExposure = case_when(
    BsmtExposure == "Ex" ~ 5,
    BsmtExposure == "Gd" ~ 4,
    BsmtExposure == "TA" ~ 3,
    BsmtExposure == "Fa" ~ 2,
    BsmtExposure == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
    mutate(Heating = case_when(
    Heating == "Floor" ~ 6,
    Heating == "GasA" ~ 5,
    Heating == "GasW" ~ 4,
    Heating == "Grav" ~ 3,
    Heating == "OthW" ~ 2,
    Heating == "Wall" ~ 1,
    TRUE ~ 0
  ))%>%
   mutate(CentralAir = case_when(
    CentralAir == "Y" ~ 1,
    TRUE ~ 0
  ))%>%
   mutate(Heating = case_when(
    Heating == "Floor" ~ 6,
    Heating == "GasA" ~ 5,
    Heating == "GasW" ~ 4,
    Heating == "Grav" ~ 3,
    Heating == "OthW" ~ 2,
    Heating == "Wall" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(Electrical = case_when(
    Electrical == "SBrkr" ~ 5,
    Electrical == "FuseA" ~ 4,
    Electrical == "FuseF" ~ 3,
    Electrical == "FuseP" ~ 2,
    Electrical == "Mix" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(KitchenQual = case_when(
    KitchenQual == "Ex" ~ 5,
    KitchenQual == "Gd" ~ 4,
    KitchenQual == "TA" ~ 3,
    KitchenQual == "Fa" ~ 2,
    KitchenQual == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(FireplaceQu = case_when(
    FireplaceQu == "Ex" ~ 5,
    FireplaceQu == "Gd" ~ 4,
    FireplaceQu == "TA" ~ 3,
    FireplaceQu == "Fa" ~ 2,
    FireplaceQu == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(GarageQual = case_when(
    GarageQual == "Ex" ~ 5,
    GarageQual == "Gd" ~ 4,
    GarageQual == "TA" ~ 3,
    GarageQual == "Fa" ~ 2,
    GarageQual == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(GarageCond = case_when(
    GarageCond == "Ex" ~ 5,
    GarageCond == "TA" ~ 3,
    GarageCond == "Fa" ~ 2,
    GarageCond == "Po" ~ 1,
    TRUE ~ 0
  ))%>%
  mutate(PoolQC = case_when(
    PoolQC == "Ex" ~ 5,
    PoolQC == "Gd" ~ 4,
    PoolQC == "TA" ~ 3,
    PoolQC == "Fa" ~ 2,
    PoolQC == "Po" ~ 1,
    TRUE ~ 0
  ))

```

### Correlación y relación
``` {r correlacion}
# Extraemos la columna 'SalePrice' del dataframe
salePriceData <- datos$SalePrice

# Creamos una copia del dataframe excluyendo la columna 'Id' y seleccionando solo las columnas numéricas
datos_numerical_cp <- datos %>%
  select(-Id) %>%
  select_if(is.numeric)

# Iteramos sobre las columnas del dataframe numérico
for (col in colnames(datos_numerical_cp)) {
  colData <- datos_numerical_cp[[col]]
  
  # Suprimimos los mensajes de advertencia alrededor de cor.test
  corr_test <- suppressWarnings(cor.test(salePriceData, colData, method = "spearman"))
  
  # Extraemos el coeficiente de correlación de Spearman del resultado del test
  corr <- corr_test$estimate
  
  # Verificamos si la correlación es mayor o igual a 0.45
  if (corr >= 0.45) {
    cat(sprintf("'%s' coeficiente de correlación spearman : %f\n", col, corr))
  }
}
```

Se considera unicamente los datos que posean un resultado superior a 0.50 ya que esto nos indica una correlación fuerte. Se utiliza este tipo de relación ya que no poseen una distribución normal